### ISSUE TITLE
Rename `oneOf` to `oneOfType`

### ISSUE THREAD

**Issue by philpee2** [ciena-blueplanet/ember-prop-types#10]
For more consistency with React's propTypes. https://facebook.github.io/react/docs/reusable-components.html#prop-validation

`oneOf` enforces that the property is one of the specified values. 
`oneOfType` enforces that the property is one of the specified types.

**Comment by sandersky** [comment]
Thanks for pointing this out, I'll try to revisit the React documentation and update this repo in the near future to be more consistent. In the mean-time if you are in need of this change feel free to make a PR that simply renames `oneOf` to `oneOfType` and add `#MAJOR#` in your PR description (for the purpose of automated version bumping).

**Comment by philpee2** [comment]
It's not a huge deal, just wanted to point it out 👍
