### ISSUE TITLE
Is there an option to require that propTypes be specified on all components?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ciena-blueplanet/ember-prop-types#114]
I think this would be super helpful when introducing new devs to a code base.
How hard would it be to add? (if it doesn't already exist)

**Comment by sglanzer** [comment]
I don't believe it currently exists, but it would be pretty easy to add - initializer to extend components and a check for some kind of `none` keyword

We took a slightly different approach in our environment and created our own generators for components that include `propTypes` https://github.com/ciena-frost/ember-frost-core/blob/master/blueprints/component/files/__root__/__path__/__name__.js#L25

**Comment by NullVoxPopuli** [comment]
woah, how do you enable those es7 computed properties? https://github.com/ciena-frost/ember-frost-core/blob/master/blueprints/component/files/__root__/__path__/__name__.js#L43 O.O

what I think I'd probably prefer is just check of existence (at least set to `{}`)

**Comment by sandersky** [comment]
@NullVoxPopuli for the ES7 decorator computed properties we use https://github.com/rwjblue/ember-computed-decorators

**Comment by sandersky** [comment]
It sounds like you essentially want a check in this file https://github.com/ciena-blueplanet/ember-prop-types/blob/master/addon/extensions/component-prop-types.js

**Comment by NullVoxPopuli** [comment]
I was actually thinking more around here? https://github.com/ciena-blueplanet/ember-prop-types/blob/master/addon/mixins/prop-types.js#L61

Would need to check if `propTypesArray.length > 0` before the `propTypesArray.forEeach` loop

**Comment by sandersky** [comment]
I'm not opposed to if the feature is opt-in (as to not require a breaking change). We can think flip the default on the next major.

**Comment by sandersky** [comment]
@NullVoxPopuli sorry for taking so long to get around to this but I've finally threw a PR up to add this feature. I've also documented the config setting in the dummy app which will show up on the Github pages once this PR passes CI and is merged/published.
