### ISSUE TITLE
Issues with validating dates

### ISSUE THREAD

**Issue by Calanthe** [ciena-blueplanet/ember-prop-types#121]
Hello,

I have a date-picker component which expects `date object` as a parameter. Based on `ember-prop-types` docs I can use only `object` value. But when I use it, I've got an error that provided parameter (date) is not an object. In object validator I've noticed that you use Ember's `typeOf` method (https://www.emberjs.com/api/#method_typeOf) which returns `date` not an `object`. 
Right now I switched to `any` but maybe you should consider defining also `date` (and other values like `regexp`) in `propTypes` ?

<img width="300" alt="screen shot 2017-04-28 at 9 23 46 am" src="https://cloud.githubusercontent.com/assets/489567/25615441/6e9395dc-2f37-11e7-88f6-0199f2b470e3.png">

**Comment by dafortin** [comment]
Fixed by #130
