### ISSUE TITLE
v2.1.0 lodash dependency issue w/ ember-block-slots

### ISSUE THREAD

**Issue by JackCA** [ciena-blueplanet/ember-prop-types#19]
I recently made a PR to [ember-block-slots](https://github.com/ciena-blueplanet/ember-block-slots/pull/32) that was merged. Unfortunately, in the meantime, its dependency on this library and the recent version bump to `v2.1` has broken the app that uses ember-block-slots.

I'm getting the following error in my app:

> loader.js:218 Uncaught Error: Could not find module `lodash` imported from `ember-prop-types/mixins/prop-types`

I can't really wrap my head around whether this is an issue with `v2.1.0` itself, or whether `ember-block-slots` `package.json` is too loose with its dependency version on this library.

Locking in my app's `ember-prop-types` version to `v2.0.1` fixes this issue.

Happy to provide more context if it would be helpful.

**Comment by sandersky** [comment]
This project was previously including `ember-lodash` as a dependency but that was removed in favor of `ember-lodash-shim`. If you run `ember install ember-prop-types` it will automatically install `ember-lodash-shim` for you as a dependency. However you are also free to run `ember install ember-lodash` which will give you the dependency used by earlier versions of this project. The main difference between `ember-lodash` and `ember-lodash-shim` is that the former gives you lodash version 3.x while the latter gives you version 4.x. I hope that helped clarify.

**Comment by JackCA** [comment]
@sandersky thanks for clarifying but as a user of `ember-block-slots` (and not *this* library directly), will running `ember install ember-block-slots` do what you expect and achieve the same thing?

**Comment by JackCA** [comment]
cc @sglanzer

**Comment by sandersky** [comment]
@JackCA it looks like `ember-block-slots` does not have blueprints and thus that will not work. @sglanzer I'm filing an issue to `ember-block-slots` to add blueprints to mitigate this issue.

**Comment by sglanzer** [comment]
I'll get on this first thing this evening
