### ISSUE TITLE
Remove Dependency on Lodash

### ISSUE THREAD

**Issue by JackCA** [ciena-blueplanet/ember-prop-types#20]
[As per suggested](https://github.com/ciena-blueplanet/ember-block-slots/issues/33#issuecomment-237092628) by @sandersky, I'm opening this issue as a discussion surrounding the opportunity to make this library more light-weight by removing the lodash dependency. 

A cursory check looks like most of the usages are type checks, which I think ES6/babel provides a lot of already.

Any thoughts?

**Comment by sglanzer** [comment]
Working up a PR now - after chatting with @sandersky I see no reason to not go this route

**Comment by JackCA** [comment]
@sglanzer y'all rock :metal:

**Comment by sglanzer** [comment]
Ember itself has covers a lot with the typeOf function, some and every are in ES6 and I had to write a minor omit function and replace forIn - relatively straightforward

#21 is up for review
