### ISSUE TITLE
Allow getDefaultProps to act as a merge on `shape` props

### ISSUE THREAD

**Issue by sglanzer** [ciena-blueplanet/ember-prop-types#25]

**Comment by sandersky** [comment]
Not sure I understand the meaning of this issue. It sounds like you want `getDefaultProps()` to be able to update `propTypes` in an extend scenario but the value of what this method returns is different than that of the `propTypes` attribute. The `propTypes` attribute is an API specification whereas `getDefaultProps()` is to define the default initial values of the properties defined in the `propTypes` object.

**Comment by sglanzer** [comment]
Sorry - I'll clarify.  `shape` is valuable in a scenario where I'm passing a hash as a parameter to a component - e.g.

```
{{my-component 
  cancel=(hash
    isVisible=true
    text='Close'
  )
}}
```

In this case I would describe the shape cancel something like

```
cancel: PropTypes.shape({
  isVisible: PropTypes.bool,
  text: PropTypes.string
})
```

Note that both are optional and I would want default props - something like

```
getDefaultProps () {
  return {
    cancel: {
      isVisible: true,
      text: 'Cancel'
    }
  }
}
```

Now, if I only provide one of those properties to the component

```
{{my-component 
  cancel=(hash
    text='Close'
  )
}}
```

I would still expect the cancel property to look like

```
cancel: {
  isVisible: true,
  text: 'Close'
}
```

Which means that any properties not provided on the component interface should still be filled from the defaults (the merge).

Instead, what currently happens is that the cancel key is seen on the component interface and the default props for cancel are deleted (skipped) and we end up with

```
cancel: {
  text: 'Close'
}
```

**Comment by sandersky** [comment]
You could achieve this today with:

```js
getDefaultProps () {
  const cancel = Ember.assign(
    {
      isVisible: true,
      text: 'Cancel'
    },
    this.get('cancel')
  )

  return {
    cancel
  }
}
```

The real question is do we want to have to do the extra recursive iterations to do this in a more automated approach as you desire. I suspect that is not the common use case but I'm open to discussion of what we think is best. Also is there a use case where you'd want it to work the way it does now, at which point changing it would break that use case.

**Comment by sglanzer** [comment]
It's an interesting question - basically do we expect a provided `shape` to include every property or only required and some optional - I'd probably lean toward the latter

**Comment by sandersky** [comment]
@sglanzer are you wanting to keep this issue hanging around or have the last few PR's satisfied your needs?

**Comment by sglanzer** [comment]
I'm good, thanks @sandersky
