### ISSUE TITLE
Add documentation on how to use with prop types defined in multiple components/mixins

### ISSUE THREAD

**Issue by justinbowes** [ciena-blueplanet/ember-prop-types#63]
I have a component `foo`, and a mixin `foo-common` that adds a common API to that component. Both use ember-prop-types.

The component `foo` has a `propTypes` attribute and a `getDefaultProps()` method. So does the mixin `foo-common`.

There are two problems with the result:

1. The `propTypes` for the `foo-common` are not set, because `ember-prop-types` does not define propTypes as a `concatenatedProperty`. The `propTypes` for `foo` override those in `foo-common`.
2. The default property values for the mixin are not set, because `getDefaultProps` from `foo` similarly overrides `foo-common`.

PR pending.

**Comment by sandersky** [comment]
This is not something `ember-prop-types` really concerns itself with. If you really want to stack mixins in conjunction with `ember-prop-types` I suggest trying something along these lines:

**foo**
```js
export default Ember.Mixin.extend({
  init () {
   const propTypes = this.propTypes || {}

    this.propTypes = Ember.merge(propTypes, {
      // whatever propTypes you want to define for this mixin
    })

    this._super(...arguments)
  }
})
```

**foo-common**
```js
export default Ember.Mixin.extend({
  init () {
   const propTypes = this.propTypes || {}

    this.propTypes = Ember.merge(propTypes, {
      // whatever propTypes you want to define for this mixin
    })

    this._super(...arguments)
  }
})
```

**Comment by sandersky** [comment]
@justinbowes I'll change this issue to add documentation on this scenario.

**Comment by justinbowes** [comment]
Consider PR #64 which adds support for my use case.
