### ISSUE TITLE
npm-install-security-check can cause build failures

### ISSUE THREAD

**Issue by dfreeman** [ciena-blueplanet/ember-prop-types#67]
I can't seem to find a public repository for [npm-install-security-check](https://www.npmjs.com/package/npm-install-security-check), but its introduction in ember-prop-types is where we came across it, and it looks like @sandersky is tied to both packages.

It seems npm 2 doesn't provide strong enough ordering guarantees for what npm-install-security-check wants to accomplish. Given the `package.json` below, a fresh `npm install` will fail because cli-color's dependencies aren't yet all available when npm-install-security-check's `postinstall` hook executes. This is causing build failures for us in CI.

```json
{
  "name": "install-failure",
  "private": true,
  "dependencies": {
    "cli-color": "^1.1.0",
    "npm-install-security-check": "^1.0.2"
  }
}
```

Errors aside, this also seems like an odd judgment for an addon to be making on behalf of its consumers. I understand that the security vulnerability involved is pretty scary, but it seems like having a random smattering of dependencies issue loud warnings may not be the best way to raise awareness. 

As npm points out in the [blog post](http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability) announcing the vulnerability, there are real-world use cases that require install scripts. Legitimate packages like `phantomjs-prebuilt` will silently fail to fully install if the advice in npm-install-security-check's warning message is followed blindly.

> On balance, it’s npm’s belief that the utility of having installation scripts is greater than the risk of worms. This is a tradeoff that we will continue to evaluate.

Given the tradeoffs, it seems like users should be able to make their own informed decision about this. Currently, however, if a user reaches a different decision than any library author who's decided to include npm-install-security-check as a dependency, it means they're subjected to loud warnings any time they install, with no way to opt out.

**Comment by sandersky** [comment]
I'm curious if you are using npm 2 are you not on Node 5+? The addon [explicitly](https://github.com/ciena-blueplanet/ember-prop-types/blob/master/package.json#L17) says it is meant for Node 5+ which I'd think means it never gets used in conjunction with npm version 2. If you use an older version of Node we don't support it although it may make sense to start supporting Node 4 since it is in LTS. @sglanzer care to weight in.

In regards to the warning it writes that to stdout as to not break CI or anything. It is simply a warning to raise awareness as many Node developers are unaware of the vulnerabilities and won't actually cause any harm. It is a mere nuisance in your console you can safely ignore if you know what you're doing. I suspect that package can be updated to not rely and `cli-color` and thus should work with npm 2 and fix your build issue. I'm not keen on the idea of removing it though as I'm trying to make the web a more secure place.

**Comment by dfreeman** [comment]
We're on Node 6, but as ember-cli bundles npm@2, we use that combination in development.

I understand your goal and I think it's laudable, but with the approach you've taken what you're doing is saying "I've come to a different decision than the npm developers on whether this feature should exist, and anyone who doesn't agree but wants to use my software must consent to be nagged about it."

That's your prerogative as a maintainer, but once someone has seen the warning and decided not to heed it, it seems unfortunate that there's no way to opt out of continuing to see it indefinitely in the future.

**Comment by sandersky** [comment]
I'd be happy to see it become a configurable option where it nags you the first time but then you add some config file to your consuming project to silence it. The repo is [here](https://github.com/sandersky/npm-install-security-check) btw. If I find time to make it configurable I'll do so but may not get to this immediately. I'll also happily accept a PR against that repository if you have time to make it confugrable via a `security.yml` file or something to that effect. I'd also happily accept a PR that removes the `cli-color` dependency that is effectively breaking you right now. The only reason I used `cli-color` is to print the text out in the warning yellow color.

**Comment by sandersky** [comment]
I went ahead and published version `1.0.3` of `npm-install-security-check` which removes the `cli-color` dependency and should unblock you.

**Comment by sandersky** [comment]
Okay version `1.0.4` has also now been published and you can silence the warning by following the instructions in the [README](https://github.com/sandersky/npm-install-security-check).

**Comment by dfreeman** [comment]
@sandersky Sorry for the radio silence, I stepped away. I had been thinking an environment variable rather than something on the file system, but that works too.

I think the only thing I might change would be to add language to the warning describing how to disable it (or, if you're worried that might make it too easy, an update to the `package.json` to include a repository entry so folks can more easily find their way to the README). If you're open to that, I'd be happy to put together a PR for it tomorrow.

Thanks for the quick turnaround on all this! Really appreciate your willingness to go back and forth and reach some middle ground :)
